name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite UTC
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate growing snake animation
        run: python scripts/generate_snake.py dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake gif to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
